framework: "cohere"

mode: "completion"
batch_size: 20

# Parameters for generation
# Check the documentation: https://docs.cohere.com/reference/chat
params:
  model: "command-nightly" # This model is in active development
  max_tokens: 128
  temperature: 0.75
  k: 0
  p: 0.75
  frequency_penalty: 0.0
  presence_penalty: 0.0
  stop_sequences: []
