framework: "openai"

mode: "completion"
batch_size: 20

# API details on "completion" task can be found here: https://platform.openai.com/docs/api-reference/completions
params:  # Below shows the parameters that are passed to the API call directly
  model: "gpt-3.5-turbo-instruct"
  suffix: null
  max_tokens: 128
  temperature: 1.0
  top_p: 1
  n: 1
  stream: false
  logprobs: null
  echo: false
  stop: null
  presence_penalty: 0
  frequency_penalty: 0
  best_of: 1
  logit_bias: {}
